services:
  mongo:
    image: mongo
  reservations:
   depends_on:
     - mongo
   build: 
     context: .
     dockerfile: ./apps/reservations/Dockerfile
     target: development
   volumes:
     - .:/usr/src/app
     - /usr/src/app/node_modules
   restart: always
   ports:
     - '3000:3000'
   env_file:
     - ./apps/reservations/.env
   command: npm run start:dev reservations
  auth:
   depends_on:
     - mongo
   build: 
     context: .
     dockerfile: ./apps/auth/Dockerfile
     target: development
   volumes:
     - .:/usr/src/app
     - /usr/src/app/node_modules
   restart: always
   ports:
     - '3001:3001'
   env_file:
     - ./apps/auth/.env
   command: npm run start:dev auth
    
    