### Login
POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "email": "dasiloy@email.com",
  "password": "Password123!"
}

### Sign Up
POST http://localhost:3001/users
Content-Type: application/json

{
  "email": "dasiloy@email.com",
  "password": "Password123!"
}

### Get user info
GET http://localhost:3001/users
